# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messaging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messaging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessaging.proto\x12\tmessaging\"%\n\x13MessageSentResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\" \n\x0fRegisterRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"7\n\x07Message\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04\x66rom\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\x8d\x01\n\tMessaging\x12=\n\tSubscribe\x12\x1a.messaging.RegisterRequest\x1a\x12.messaging.Message0\x01\x12\x41\n\x0bSendMessage\x12\x12.messaging.Message\x1a\x1e.messaging.MessageSentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGESENTRESPONSE']._serialized_start=30
  _globals['_MESSAGESENTRESPONSE']._serialized_end=67
  _globals['_REGISTERREQUEST']._serialized_start=69
  _globals['_REGISTERREQUEST']._serialized_end=101
  _globals['_MESSAGE']._serialized_start=103
  _globals['_MESSAGE']._serialized_end=158
  _globals['_MESSAGING']._serialized_start=161
  _globals['_MESSAGING']._serialized_end=302
# @@protoc_insertion_point(module_scope)
