# Permite que o Mosquitto escreva logs
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

listener 8883 0.0.0.0

# Caminho para os ficheiros
cafile /mosquitto/config/certs/rootCA.crt
certfile /mosquitto/config/certs/mosquitto.crt
keyfile /mosquitto/config/certs/mosquitto.key
crlfile /mosquitto/config/certs/revoked.crl

# Obriga os clientes a enviarem um certificado
require_certificate true

# Usar o "Common Name" (CN) do certificado do cliente como "username".
use_identity_as_username true

# Como estamos usando os certificados para autenticar,não precisamos de ficheiro de passwords
allow_anonymous false

# aponta para o arquivo de regras de acesso
acl_file /mosquitto/config/regras_acesso.acl
