#include "h2.h"
#include "h2client.h"

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"

#include <string.h>
#include <netdb.h>
#include <stdbool.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/socket.h>

#include <nghttp2/nghttp2.h>

#include "log.h"
#include "esp_timer.h"
#include "esp_err.h"
#include "esp_tls.h"
#include "esp_tls_errors.h"

/*
 * Weak declarations for embedded TLS material.
 * When building without embedded certs (h2c / plain TCP mode), these symbols
 * are absent at link time. The __attribute__((weak)) prevents linker errors;
 * h2client_load_certs_into_cfg() checks for NULL before using them.
 */
extern const uint8_t _binary_ca_crt_start[]    __attribute__((weak));
extern const uint8_t _binary_ca_crt_end[]      __attribute__((weak));
extern const uint8_t _binary_esp32_crt_start[] __attribute__((weak));
extern const uint8_t _binary_esp32_crt_end[]   __attribute__((weak));
extern const uint8_t _binary_esp32_key_start[] __attribute__((weak));
extern const uint8_t _binary_esp32_key_end[]   __attribute__((weak));

/* Alternative symbol names generated by CMake EMBED_TXTFILES path variants */
extern const unsigned char ca_crt_start[] asm("_binary_certs_ca_crt_start") __attribute__((weak));
extern const unsigned char ca_crt_end[]   asm("_binary_certs_ca_crt_end")   __attribute__((weak));
extern const uint8_t esp32_crt_start[]  asm("_binary_certs_esp32_crt_start") __attribute__((weak));
extern const uint8_t esp32_crt_end[]    asm("_binary_certs_esp32_crt_end")   __attribute__((weak));
extern const uint8_t esp32_key_start[]  asm("_binary_certs_esp32_key_start") __attribute__((weak));
extern const uint8_t esp32_key_end[]    asm("_binary_certs_esp32_key_end")   __attribute__((weak));
extern const uint8_t esp32_crt2_start[] asm("_binary_esp32_crt_start") __attribute__((weak));
extern const uint8_t esp32_crt2_end[]   asm("_binary_esp32_crt_end")   __attribute__((weak));
extern const uint8_t esp32_key2_start[] asm("_binary_esp32_key_start") __attribute__((weak));
extern const uint8_t esp32_key2_end[]   asm("_binary_esp32_key_end")   __attribute__((weak));


#define H2CLIENT_TASK_STACKSIZE		CONFIG_H2CLIENT_TASK_STACKSIZE
#define H2CLIENT_TASK_PRIORITY		5
#define H2CLIENT_REQUEST_QUEUE_LENGTH	5

#define H2CLIENT_TIMEOUT_REQUEST_MS	30000

#define H2CLIENT_TIMEOUT_ACQ_SEMAPHORE	500

#define ms_to_ticks(d_ms)		(TickType_t)(d_ms / portTICK_PERIOD_MS)
#define min(a, b)			(a < b?a:b)

#define h2client_request_internal_initialize()	{ \
	.h2_stream_id = -1, \
	.error = false \
}

enum connection_state{
	CONN_EMPTY,
	CONN_CONFIGURED,
	CONN_CONNECTED
};

struct parsed_url{
	const char * protocol;
	unsigned int protocol_length;
	const char * host;
	unsigned int host_length;
	const char * service;
	unsigned int service_length;
	const char * path;
	unsigned int path_length;
	bool is_tls;
};

struct server{
	char * protocol;
	char * host;
	char * service;
	bool is_tls;
};

struct h2client_connection_handle{
	struct h2_connection conn;

	nghttp2_session * h2_session;

	enum connection_state state;
	struct server server;
	SemaphoreHandle_t semaphore;
	QueueHandle_t request_queue;
	struct h2client_request_internal * current_request;
	uint64_t last_used;
};

struct h2client_request_internal{
	struct h2client_request * original_request;
	int h2_stream_id;
	const char * path;
	SemaphoreHandle_t wait_semaphore;
#ifdef CONFIG_SUPPORT_STATIC_ALLOCATION
	StaticSemaphore_t wait_semaphore_store;
#endif
	bool error;
};

extern ssize_t h2_nghttp2_callback_recv(nghttp2_session * session, uint8_t * buf, size_t length, int flags, void * user_data);
extern ssize_t h2_nghttp2_callback_send(nghttp2_session * session, const uint8_t * data, size_t length, int flags, void * user_data);

static void task(void *args);
static struct h2client_connection_handle * request_new_connection(const struct parsed_url * url);

static bool request(struct h2client_connection_handle * handle, struct h2client_request_internal * request);

static bool connect_socket(struct server * url, int * fd);
static bool connect_tls(struct h2client_connection_handle * handle);
static bool connect_plain(struct h2client_connection_handle * handle);
static bool connect_h2(struct h2client_connection_handle * handle);

static bool h2client_handle(struct h2client_connection_handle * handle);

static int callback_on_frame_recv(nghttp2_session * session, const nghttp2_frame * frame, void * user_data);
static int callback_on_data_chunk_recv(nghttp2_session * session, uint8_t flags, int32_t stream_id, const uint8_t * data, size_t len, void * user_data);
static int callback_on_stream_close(nghttp2_session * session, int32_t stream_id, uint32_t error_code, void * user_data);
static int callback_on_header(nghttp2_session * session, const nghttp2_frame * frame, const uint8_t * name, size_t namelen, const uint8_t * value, size_t valuelen, uint8_t flags, void * user_data);

static struct h2client_connection_handle * get_store(const char * protocol, const char * host, const char * service);
static struct h2client_connection_handle * get_store_by_parsed_url(const struct parsed_url * url);
static struct h2client_connection_handle * get_empty_store();
static struct h2client_connection_handle * get_idle_store();
static void free_connection_handle(struct h2client_connection_handle * handle);

bool parse_url(const char * url, struct parsed_url * output);

static ssize_t handle_request_data(nghttp2_session *session, int32_t stream_id, uint8_t *buf, size_t length, uint32_t *data_flags, nghttp2_data_source *source, void *user_data);
static int handle_response_data(struct h2client_connection_handle * handle, const char * data, size_t len, int flags);

static const char * TAG = "h2client";
static const char default_path[] = "/";

static TaskHandle_t task_handle;
static struct h2client_connection_handle connections[CONFIG_H2CLIENT_CONCURRENT_CONNECTIONS];
static volatile unsigned int new_connection_id = 0;
static esp_tls_cfg_t g_tls_cfg;
static bool g_tls_cfg_ready = false;
static const char *g_alpn_protos[] = {"h2", NULL};

static inline bool pick_embedded_range(const uint8_t* s1, const uint8_t* e1,
                                       const uint8_t* s2, const uint8_t* e2,
                                       const uint8_t** out_s, int* out_len)
{
    if (s1 && e1 && e1 > s1) { *out_s = s1; *out_len = (int)(e1 - s1); return true; }
    if (s2 && e2 && e2 > s2) { *out_s = s2; *out_len = (int)(e2 - s2); return true; }
    *out_s = NULL; *out_len = 0; return false;
}

static bool h2client_load_certs_into_cfg(void);

static nghttp2_session_callbacks * nghttp2_callbacks = NULL;


static bool h2client_load_certs_into_cfg(void)
{
    /* Weak symbols decay to NULL when undefined; use pointer variables to compare safely */
    const uint8_t *p_ca_start = _binary_ca_crt_start;
    const uint8_t *p_ca_end   = _binary_ca_crt_end;

    if (!p_ca_start || !p_ca_end || p_ca_end == p_ca_start) {
        log(ERROR, TAG, "CA cert not embedded (required for TLS). Check CMake EMBED_TXTFILES.");
        return false;
    }

    const unsigned char *ca_pem = (const unsigned char *)p_ca_start;
    size_t ca_len = (size_t)(p_ca_end - p_ca_start);

    memset(&g_tls_cfg, 0, sizeof(g_tls_cfg));

    g_tls_cfg.cacert_buf   = ca_pem;
    g_tls_cfg.cacert_bytes = (unsigned int)ca_len;

    /* Client cert+key are optional (one-way TLS only) */
    const uint8_t *crt_pem = NULL; int crt_len = 0;
    const uint8_t *key_pem = NULL; int key_len = 0;
    pick_embedded_range(_binary_esp32_crt_start, _binary_esp32_crt_end,
                        esp32_crt2_start,        esp32_crt2_end,
                        &crt_pem, &crt_len);
    pick_embedded_range(_binary_esp32_key_start, _binary_esp32_key_end,
                        esp32_key2_start,        esp32_key2_end,
                        &key_pem, &key_len);

    if (crt_pem && crt_len > 0) {
        g_tls_cfg.clientcert_buf   = crt_pem;
        g_tls_cfg.clientcert_bytes = (unsigned int)crt_len;
    }
    if (key_pem && key_len > 0) {
        g_tls_cfg.clientkey_buf    = key_pem;
        g_tls_cfg.clientkey_bytes  = (unsigned int)key_len;
    }

    g_tls_cfg.alpn_protos = g_alpn_protos;

    g_tls_cfg_ready = true;
    return true;
}


int h2client_initialize()
{
    unsigned int i;

    /* TLS cert loading is deferred to connect_tls() — only needed for https:// connections */

    nghttp2_session_callbacks_new(&nghttp2_callbacks);
    nghttp2_session_callbacks_set_send_callback(nghttp2_callbacks, h2_nghttp2_callback_send);
    nghttp2_session_callbacks_set_recv_callback(nghttp2_callbacks, h2_nghttp2_callback_recv);
    nghttp2_session_callbacks_set_on_frame_recv_callback(nghttp2_callbacks, callback_on_frame_recv);
    nghttp2_session_callbacks_set_on_stream_close_callback(nghttp2_callbacks, callback_on_stream_close);
    nghttp2_session_callbacks_set_on_data_chunk_recv_callback(nghttp2_callbacks, callback_on_data_chunk_recv);
    nghttp2_session_callbacks_set_on_header_callback(nghttp2_callbacks, callback_on_header);

    memset(connections, 0, sizeof(connections));

    for(i = 0; i < (sizeof(connections) / sizeof(connections[0])); i++){
        struct h2client_connection_handle * handle = &(connections[i]);

        handle->request_queue = xQueueCreate(H2CLIENT_REQUEST_QUEUE_LENGTH, sizeof(struct h2client_request_internal *));
        if(handle->request_queue == NULL){
            return H2_ERROR_NO_MEM;
        }

        handle->conn.tls = NULL;
        handle->conn.sockfd = -1;
        handle->last_used = 0;

        handle->semaphore = xSemaphoreCreateBinary();
        if(handle->semaphore == NULL){
            return H2_ERROR_NO_MEM;
        }
        xSemaphoreGive(handle->semaphore);
    }

    if(xTaskCreate(task, "h2client_task", H2CLIENT_TASK_STACKSIZE, NULL, H2CLIENT_TASK_PRIORITY, &task_handle) != pdPASS){
        return H2_ERROR_NO_MEM;
    }

    return H2_ERROR_OK;
}


void h2client_deinitialize(void)
{
	int i;

	for(i = 0; i < (sizeof(connections) / sizeof(connections[0])); i++){
		struct h2client_connection_handle * handle = &(connections[i]);

		if(xSemaphoreTake(connections[i].semaphore, ms_to_ticks(H2CLIENT_TIMEOUT_ACQ_SEMAPHORE))){
			vQueueDelete(handle->request_queue);
			free_connection_handle(handle);
			vSemaphoreDelete(handle->semaphore);
		}
	}

	nghttp2_session_callbacks_del(nghttp2_callbacks);

	vTaskDelete(task_handle);
}

bool h2client_do_request(struct h2client_request * request)
{
	struct parsed_url url;

	if(!parse_url(request->url, &url)){
		log(ERROR, TAG, "Invalid server url: %s", request->url);
		return false;
	}

	struct h2client_connection_handle * handle = get_store_by_parsed_url(&url);
	if(handle == NULL){
		handle = request_new_connection(&url);
		if(handle == NULL){
			log(INFO, TAG, "Error setting up connection config for: %s", request->url);
			return false;
		}
	}else{
		log(INFO, TAG, "Reusing existing connection for: %s", request->url);
	}
	handle->last_used = esp_timer_get_time();

	struct h2client_request_internal r = h2client_request_internal_initialize();
	struct h2client_request_internal * r_ptr = &r;
	r.path = url.path;
	r.original_request = request;
#ifdef CONFIG_SUPPORT_STATIC_ALLOCATION
	r.wait_semaphore = xSemaphoreCreateBinaryStatic(&(r.wait_semaphore_store));
#else
	r.wait_semaphore = xSemaphoreCreateBinary();
#endif
	if(r.wait_semaphore == NULL){
		log(ERROR, TAG, "Unable to create wait semaphore");
		return false;
	}

	if(xQueueSendToBack(handle->request_queue, &r_ptr, (TickType_t)0)){
		bool error = false;
		unsigned int timeout_ms = H2CLIENT_TIMEOUT_REQUEST_MS;
		if(request->timeout_ms > 0){
			timeout_ms = request->timeout_ms;
		}

		xSemaphoreGive(handle->semaphore);

		log(INFO, TAG, "Waiting for request to complete");

		if(xSemaphoreTake(r.wait_semaphore, ms_to_ticks(timeout_ms))){
			error = r.error;
			log(INFO, TAG, "Request complete");

			if(xSemaphoreTake(handle->semaphore, ms_to_ticks(H2CLIENT_TIMEOUT_ACQ_SEMAPHORE))){
				handle->current_request = NULL;
				xSemaphoreGive(handle->semaphore);
			}else{
				log(ERROR, TAG, "Error acquiring lock to close request");
				handle->current_request = NULL;
			}
		}else{
			error = true;
			log(ERROR, TAG, "Waited too long for request to finish");

			if(xSemaphoreTake(handle->semaphore, ms_to_ticks(H2CLIENT_TIMEOUT_ACQ_SEMAPHORE))){
				free_connection_handle(handle);
				xSemaphoreGive(handle->semaphore);
			}else{
				log(ERROR, TAG, "Error acquiring lock to close timed out request");
			}
		}

		vSemaphoreDelete(r.wait_semaphore);
		return !error;
	}else{
		log(ERROR, TAG, "Queue full for connection: %s", request->url);
		xSemaphoreGive(handle->semaphore);
		return false;
	}
}

bool h2client_disconnect(const char * protocol, const char * host, const char * service)
{
	struct h2client_connection_handle * handle = get_store(protocol, host, service);
	if(handle != NULL){
		free_connection_handle(handle);
		xSemaphoreGive(handle->semaphore);
		return true;
	}
	return false;
}


static void task(void *args)
{
	int i;
	while(true){
		for(i = 0; i < (sizeof(connections) / sizeof(connections[0])); i++){
			struct h2client_connection_handle * handle = &connections[i];

			if(xSemaphoreTake(handle->semaphore, ms_to_ticks(H2CLIENT_TIMEOUT_ACQ_SEMAPHORE))){
				switch(handle->state){
					case CONN_CONFIGURED:
						{
							bool transport_ok;
							if (handle->server.is_tls) {
								transport_ok = connect_tls(handle);
							} else {
								transport_ok = connect_plain(handle);
							}
							if(transport_ok && connect_h2(handle)){
								log(INFO, TAG, "Connection %u: Connected", handle->conn.id);
								handle->state = CONN_CONNECTED;
							}else{
								log(ERROR, TAG, "Connection %u: Error setting up transport/HTTP2", handle->conn.id);
								free_connection_handle(handle);
							}
						}
						break;
					case CONN_CONNECTED:
						if(handle->current_request != NULL){
							if(!h2client_handle(handle)){
								log(ERROR, TAG, "Connection %u: Error in send or receive", handle->conn.id);
								free_connection_handle(handle);
							}
						}else{
							if(xQueueReceive(handle->request_queue, &(handle->current_request), 0)){
								log(INFO, TAG, "Connection %u: [%s] %s",
										handle->conn.id,
										h2_method_to_string(handle->current_request->original_request->method),
										handle->current_request->path);
								request(handle, handle->current_request);
							}
						}
						break;
					case CONN_EMPTY:
						break;
					default:
						log(ERROR, TAG, "Connection %u: Unknown state (%d)", handle->conn.id, handle->state);
						break;
				}
				xSemaphoreGive(handle->semaphore);
			}else{
				log(ERROR, TAG, "Connection %u: Error obtaining semaphore", handle->conn.id);
			}
		}
		vTaskDelay(2);
	}
}


static bool request(struct h2client_connection_handle * handle, struct h2client_request_internal * request)
{
	const char * m = h2_method_to_string(request->original_request->method);
	int stream_id = -1;

	static const char hdr_te_name[] = "te";
	static const char hdr_te_val[]  = "trailers";

	nghttp2_nv hdrs[6];
	unsigned int hdrs_items = 0;

	hdrs[hdrs_items++] = h2_make_nv(h2_header_method,    sizeof(h2_header_method)    - 1, m,                      strlen(m));
	hdrs[hdrs_items++] = h2_make_nv(h2_header_scheme,    sizeof(h2_header_scheme)    - 1, handle->server.protocol, strlen(handle->server.protocol));
	hdrs[hdrs_items++] = h2_make_nv(h2_header_authority, sizeof(h2_header_authority) - 1, handle->server.host,     strlen(handle->server.host));
	hdrs[hdrs_items++] = h2_make_nv(h2_header_path,      sizeof(h2_header_path)      - 1, request->path,           strlen(request->path));
	hdrs[hdrs_items++] = h2_make_nv(hdr_te_name,         sizeof(hdr_te_name)         - 1, hdr_te_val,              sizeof(hdr_te_val) - 1);

	if(request->original_request->requestbody.content_type != NULL){
		h2_assign_nv(&hdrs[hdrs_items++], h2_header_contenttype, sizeof(h2_header_contenttype) - 1,
			request->original_request->requestbody.content_type,
			strlen(request->original_request->requestbody.content_type));
	}

	if(request->original_request->method == H2_GET){
		stream_id = nghttp2_submit_request(handle->h2_session, NULL, hdrs, hdrs_items, NULL, NULL);
	}else if(request->original_request->method == H2_PUT || request->original_request->method == H2_POST){
		nghttp2_data_provider p;
		p.read_callback = handle_request_data;
		p.source.ptr = NULL;
		stream_id = nghttp2_submit_request(handle->h2_session, NULL, hdrs, hdrs_items, &p, NULL);
	}else{
		log(ERROR, TAG, "Connection %u: Unknown http2 method: %d", handle->conn.id, request->original_request->method);
	}

	if(stream_id < 0){
		log(ERROR, TAG, "Connection %u: Error prepping headers", handle->conn.id);
		return false;
	}

	log(INFO, TAG, "Connection %u: stream id %d", handle->conn.id, stream_id);
	handle->current_request->h2_stream_id = stream_id;
	return true;
}


static bool connect_socket(struct server * server, int * fd)
{
	struct addrinfo hints = {
		.ai_family = AF_UNSPEC,
		.ai_socktype = SOCK_STREAM
	};
	struct addrinfo * res;
	int r, sockfd;

	r = getaddrinfo(server->host, server->service, &hints, &res);
	if(r){
		log(ERROR, TAG, "getaddrinfo error: %d", r);
		goto err_addrinfo;
	}

	sockfd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);
	if(sockfd < 0){
		goto err_socket;
	}

	r = connect(sockfd, res->ai_addr, res->ai_addrlen);
	if(r < 0){
		goto err_connect;
	}

	freeaddrinfo(res);
	*fd = sockfd;
	return true;

err_connect:
	close(sockfd);
err_socket:
	freeaddrinfo(res);
err_addrinfo:
	return false;
}

/**
 * Establish a plain TCP connection for h2c (HTTP/2 cleartext).
 * Sets conn.sockfd to non-blocking; conn.tls remains NULL.
 */
static bool connect_plain(struct h2client_connection_handle * handle)
{
	int sockfd, flags;

	if (handle->conn.sockfd >= 0) {
		return true; /* already connected */
	}

	if (!connect_socket(&handle->server, &sockfd)) {
		log(ERROR, TAG, "Connection %u: TCP connect failed (host=%s port=%s)",
			handle->conn.id, handle->server.host, handle->server.service);
		return false;
	}

	handle->conn.sockfd = sockfd;
	handle->conn.tls    = NULL;

	flags = fcntl(sockfd, F_GETFL, 0);
	fcntl(sockfd, F_SETFL, flags | O_NONBLOCK);

	log(INFO, TAG, "Connection %u: plain TCP connected to %s:%s",
		handle->conn.id, handle->server.host, handle->server.service);
	return true;
}

static bool connect_tls(struct h2client_connection_handle * handle)
{
    int r, flags;
    int port = 0;

    if(!g_tls_cfg_ready){
        if(!h2client_load_certs_into_cfg()){
            return false;
        }
    }

    port = atoi(handle->server.service);
    if(port <= 0){
        log(ERROR, TAG, "Invalid port/service: %s", handle->server.service);
        return false;
    }

    if(handle->conn.tls){
        return true;
    }

    handle->conn.tls = esp_tls_init();
    if(handle->conn.tls == NULL){
        log(ERROR, TAG, "esp_tls_init failed");
        return false;
    }

    esp_tls_cfg_t cfg = g_tls_cfg;
    cfg.timeout_ms = 20000;
    cfg.alpn_protos = g_alpn_protos;

    r = esp_tls_conn_new_sync(handle->server.host, (int)strlen(handle->server.host), port, &cfg, handle->conn.tls);
    if(r != 1){
        int esp_tls_code = 0;
        int esp_tls_flags = 0;
        esp_tls_error_handle_t err_handle = NULL;
        if (esp_tls_get_error_handle(handle->conn.tls, &err_handle) == ESP_OK && err_handle) {
            esp_tls_get_and_clear_last_error(err_handle, &esp_tls_code, &esp_tls_flags);
        }
        log(ERROR, TAG, "Connection %u: esp_tls_conn_new_sync failed (host=%s port=%d, mbedtls=0x%x flags=0x%x)",
            handle->conn.id, handle->server.host, port, esp_tls_code, esp_tls_flags);
        esp_tls_conn_destroy(handle->conn.tls);
        handle->conn.tls = NULL;
        return false;
    }

    if(esp_tls_get_conn_sockfd(handle->conn.tls, &handle->conn.sockfd) != ESP_OK){
        log(WARN, TAG, "Connection %u: could not obtain sockfd from esp_tls", handle->conn.id);
        handle->conn.sockfd = -1;
    }else{
        flags = fcntl(handle->conn.sockfd, F_GETFL, 0);
        fcntl(handle->conn.sockfd, F_SETFL, flags | O_NONBLOCK);
    }

    return true;
}


static bool connect_h2(struct h2client_connection_handle * handle)
{
	if(nghttp2_session_client_new(&handle->h2_session, nghttp2_callbacks, handle) != 0){
		log(ERROR, TAG, "Connection %d: Unable to start new session", handle->conn.id);
		return false;
	}

	if(nghttp2_submit_settings(handle->h2_session, NGHTTP2_FLAG_NONE, NULL, 0) != 0){
		log(ERROR, TAG, "Connection %d: Error submitting session", handle->conn.id);
		nghttp2_session_del(handle->h2_session);
		return false;
	}

	return true;
}


static bool h2client_handle(struct h2client_connection_handle * handle)
{
	int r;

	if((r = nghttp2_session_send(handle->h2_session)) != 0){
		log(ERROR, TAG, "Connection %d: Send failed (error %d)", handle->conn.id, r);
		return false;
	}

	if((r = nghttp2_session_recv(handle->h2_session)) != 0){
		log(ERROR, TAG, "Connection %d: Receive failed (error %d)", handle->conn.id, r);
		return false;
	}
	return true;
}


static int handle_response_data(struct h2client_connection_handle * handle, const char * data, size_t length, int flags)
{
	if(length){
		log(DEBUG, TAG, "data received (%uB)", length);

		switch(handle->current_request->original_request->responsebody.method){
			case H2_HANDLEBODY_BUFFER:
				{
					struct h2client_responsebody * r = &handle->current_request->original_request->responsebody;
					int copy_bytes = min(r->buffer_size - r->size, length);
					if(copy_bytes < (int)length){
						log(WARNING, TAG, "responsebody buffer full, skipping bytes");
					}
					if(copy_bytes > 0){
						memcpy(&(r->buffer[r->size]), data, copy_bytes);
						r->size += copy_bytes;
					}
				}
				break;
			case H2_HANDLEBODY_CALLBACK:
				handle->current_request->original_request->responsebody.callback(data, length);
				break;
			case H2_HANDLEBODY_NONE:
			default:
				break;
		}
	}

	if(flags & H2_FLAG_STREAM_CLOSE){
		xSemaphoreGive(handle->current_request->wait_semaphore);
	}

	return 0;
}

static ssize_t handle_request_data(nghttp2_session *session, int32_t stream_id, uint8_t *buf, size_t length, uint32_t *data_flags, nghttp2_data_source *source, void *user_data)
{
	int copied_bytes = 0;
	bool finished = false;

	struct h2client_connection_handle * handle = user_data;

	switch(handle->current_request->original_request->requestbody.method){
		case H2_HANDLEBODY_BUFFER:
			{
				struct h2client_requestbody * r = &handle->current_request->original_request->requestbody;
				copied_bytes = min(r->size, length);
				memcpy(buf, &(r->body[r->written]), copied_bytes);
				r->written += copied_bytes;
				finished = r->written >= r->size;
			}
			break;
		case H2_HANDLEBODY_CALLBACK:
			copied_bytes = handle->current_request->original_request->requestbody.callback((char *)buf, length, &finished);
			break;
		case H2_HANDLEBODY_NONE:
		default:
			finished = true;
			break;
	}

	if(finished){
		*data_flags |= NGHTTP2_DATA_FLAG_EOF;
	}

	return copied_bytes;
}


static int callback_on_frame_recv(nghttp2_session * session, const nghttp2_frame * frame, void * user_data)
{
	struct h2client_connection_handle * handle = user_data;
	switch(frame->hd.type){
		case NGHTTP2_HEADERS:
			break;
		case NGHTTP2_DATA:
			if(handle->current_request->h2_stream_id == frame->hd.stream_id){
				return handle_response_data(handle, NULL, 0, H2_FLAG_RECEIVE_FRAME_COMPLETE);
			}
			break;
		default:
			break;
	}
	return 0;
}

static int callback_on_data_chunk_recv(nghttp2_session * session, uint8_t flags, int32_t stream_id, const uint8_t * data, size_t len, void * user_data)
{
	struct h2client_connection_handle * handle = user_data;
	if(handle->current_request->h2_stream_id == stream_id){
		return handle_response_data(handle, (char *)data, len, 0);
	}
	return 0;
}

static int callback_on_stream_close(nghttp2_session * session, int32_t stream_id, uint32_t error_code, void * user_data)
{
	struct h2client_connection_handle * handle = user_data;
	if(handle->current_request->h2_stream_id == stream_id){
		return handle_response_data(handle, NULL, 0, H2_FLAG_STREAM_CLOSE);
	}
	return 0;
}

static int callback_on_header(nghttp2_session * session, const nghttp2_frame * frame, const uint8_t * name, size_t namelen, const uint8_t * value, size_t valuelen, uint8_t flags, void * user_data)
{
	struct h2client_connection_handle * handle = user_data;

	static const char grpc_status[]  = "grpc-status";
	static const char grpc_message[] = "grpc-message";

	switch(frame->hd.type){
		case NGHTTP2_HEADERS:
			if((frame->headers.cat == NGHTTP2_HCAT_RESPONSE || frame->headers.cat == NGHTTP2_HCAT_HEADERS)
				&& handle->current_request != NULL
				&& handle->current_request->h2_stream_id == frame->hd.stream_id){

				if(strncmp(h2_header_status, (char *)name, namelen) == 0){
					int status = strtol((char *)value, NULL, 10);
					handle->current_request->original_request->status = status;
					log(INFO, TAG, "Status code: %d", status);
				}

				if(namelen == (sizeof(grpc_status) - 1) && memcmp(name, grpc_status, sizeof(grpc_status) - 1) == 0){
					log(INFO, TAG, "grpc-status: %.*s", (int)valuelen, (const char *)value);
				}
				if(namelen == (sizeof(grpc_message) - 1) && memcmp(name, grpc_message, sizeof(grpc_message) - 1) == 0){
					log(INFO, TAG, "grpc-message: %.*s", (int)valuelen, (const char *)value);
				}
			}
			break;
		default:
			break;
	}
	return 0;
}


static struct h2client_connection_handle * request_new_connection(const struct parsed_url * url)
{
	struct h2client_connection_handle * handle = get_empty_store();

	if(handle == NULL){
		handle = get_idle_store();
	}

	if(handle != NULL){
		handle->server.protocol = malloc(url->protocol_length + 1);
		if(handle->server.protocol == NULL){
			xSemaphoreGive(handle->semaphore);
			return NULL;
		}
		handle->server.host = malloc(url->host_length + 1);
		if(handle->server.host == NULL){
			free(handle->server.protocol);
			xSemaphoreGive(handle->semaphore);
			return NULL;
		}
		handle->server.service = malloc(url->service_length + 1);
		if(handle->server.service == NULL){
			free(handle->server.protocol);
			free(handle->server.host);
			xSemaphoreGive(handle->semaphore);
			return NULL;
		}

		memcpy(handle->server.protocol, url->protocol, url->protocol_length);
		handle->server.protocol[url->protocol_length] = '\0';
		memcpy(handle->server.host, url->host, url->host_length);
		handle->server.host[url->host_length] = '\0';
		memcpy(handle->server.service, url->service, url->service_length);
		handle->server.service[url->service_length] = '\0';
		handle->server.is_tls = url->is_tls;

		handle->conn.id = new_connection_id++;
		log(INFO, TAG, "Prepped connection: %s://%s:%s (tls=%d) ID: %u",
			handle->server.protocol, handle->server.host, handle->server.service,
			(int)handle->server.is_tls, handle->conn.id);

		handle->state = CONN_CONFIGURED;
	}else{
		log(ERROR, TAG, "No connection store available");
	}
	return handle;
}

static struct h2client_connection_handle * get_store(const char * protocol, const char * host, const char * service)
{
	unsigned int i;
	for(i = 0; i < (sizeof(connections) / sizeof(connections[0])); i++){
		if(xSemaphoreTake(connections[i].semaphore, ms_to_ticks(H2CLIENT_TIMEOUT_ACQ_SEMAPHORE))){
			if(connections[i].state != CONN_EMPTY){
				if(strcmp(connections[i].server.protocol, protocol) == 0
					&& strcmp(connections[i].server.host, host) == 0
					&& strcmp(connections[i].server.service, service) == 0){
					return &(connections[i]);
				}
			}
			xSemaphoreGive(connections[i].semaphore);
		}
	}
	return NULL;
}

static struct h2client_connection_handle * get_store_by_parsed_url(const struct parsed_url * url)
{
	unsigned int i;
	for(i = 0; i < (sizeof(connections) / sizeof(connections[0])); i++){
		if(xSemaphoreTake(connections[i].semaphore, ms_to_ticks(H2CLIENT_TIMEOUT_ACQ_SEMAPHORE))){
			if(connections[i].state != CONN_EMPTY
				&& connections[i].current_request == NULL
				&& uxQueueMessagesWaiting(connections[i].request_queue) == 0){
				if(strncmp(connections[i].server.protocol, url->protocol, url->protocol_length) == 0
					&& strncmp(connections[i].server.host, url->host, url->host_length) == 0
					&& strncmp(connections[i].server.service, url->service, url->service_length) == 0
					){
					return &(connections[i]);
				}
			}
			xSemaphoreGive(connections[i].semaphore);
		}
	}
	return NULL;
}

static struct h2client_connection_handle * get_empty_store()
{
	unsigned int i;
	for(i = 0; i < (sizeof(connections) / sizeof(connections[0])); i++){
		if(xSemaphoreTake(connections[i].semaphore, ms_to_ticks(H2CLIENT_TIMEOUT_ACQ_SEMAPHORE))){
			if(connections[i].state == CONN_EMPTY){
				return &(connections[i]);
			}
			xSemaphoreGive(connections[i].semaphore);
		}
	}
	return NULL;
}

static struct h2client_connection_handle * get_idle_store()
{
	unsigned int i;
	struct h2client_connection_handle * oldest = &(connections[0]);

	for(i = 1; i < (sizeof(connections) / sizeof(connections[0])); i++){
		if(connections[i].last_used < oldest->last_used){
			oldest = &(connections[i]);
		}
	}

	if(xSemaphoreTake(oldest->semaphore, ms_to_ticks(H2CLIENT_TIMEOUT_ACQ_SEMAPHORE))){
		if(oldest->current_request == NULL && uxQueueMessagesWaiting(oldest->request_queue) == 0){
			log(INFO, TAG, "Cleanup idle connection %d", oldest->conn.id);
			free_connection_handle(oldest);
			return oldest;
		}
		xSemaphoreGive(oldest->semaphore);
	}

	return NULL;
}

static void free_connection_handle(struct h2client_connection_handle * handle)
{
	struct h2client_request_internal * r;

	if(handle->current_request != NULL){
		handle->current_request->error = true;
		xSemaphoreGive(handle->current_request->wait_semaphore);
		log(WARNING, TAG, "Connection %d: Cancelled current request", handle->conn.id);
		handle->current_request = NULL;
	}

	while(xQueueReceive(handle->request_queue, &r, 0)){
		r->error = true;
		xSemaphoreGive(r->wait_semaphore);
		log(WARNING, TAG, "Connection %d: Cancelled request in queue", handle->conn.id);
	}

	if(handle->h2_session != NULL){
		nghttp2_session_del(handle->h2_session);
		handle->h2_session = NULL;
	}

	if(handle->conn.tls != NULL){
		/* TLS: esp_tls_conn_destroy closes the underlying socket */
		esp_tls_conn_destroy(handle->conn.tls);
		handle->conn.tls = NULL;
	} else if(handle->conn.sockfd >= 0){
		/* Plain TCP: close the socket manually */
		close(handle->conn.sockfd);
	}
	handle->conn.sockfd = -1;

	free(handle->server.protocol);
	handle->server.protocol = NULL;
	free(handle->server.host);
	handle->server.host = NULL;
	free(handle->server.service);
	handle->server.service = NULL;

	log(INFO, TAG, "free done");
	handle->state = CONN_EMPTY;
}


bool parse_url(const char * url, struct parsed_url * output)
{
	size_t len, i, offset, tmp_len;
	const char * tmp;

	len = strlen(url);

	if (len >= 8 && memcmp("https://", url, 8) == 0) {
		output->protocol        = url;
		output->protocol_length = 5; /* "https" */
		output->is_tls          = true;
		offset = 8;
	} else if (len >= 7 && memcmp("http://", url, 7) == 0) {
		output->protocol        = url;
		output->protocol_length = 4; /* "http" */
		output->is_tls          = false;
		offset = 7;
	} else {
		return false;
	}

	tmp = &(url[offset]);
	tmp_len = 0;
	if (url[offset] == '['){
		offset++;
		tmp++;
		for(i = offset; i < len; i++){
			if (url[i] == ']'){
				tmp_len = i - offset;
				offset = i + 1;
				break;
			}
		}
	} else {
		const char delims[] = ":/?#";
		for(i = offset; i < len; i++){
			if(strchr(delims, url[i]) != NULL){
				break;
			}
		}
		tmp_len = i - offset;
		offset = i;
	}
	if(tmp_len == 0){
		return false;
	}
	output->host = tmp;
	output->host_length = tmp_len;

	tmp_len = 0;
	if(offset < len && url[offset] == ':') {
		const char delims[] = "/?#";
		offset++;
		tmp = &(url[offset]);
		for(i = offset; i < len; i++){
			if(strchr(delims, url[i]) != NULL){
				break;
			}
			if(url[i] < '0' || url[i] > '9'){
				return false;
			}
			if(i - offset > 4){
				return false;
			}
			if(i - offset == 4){
				if(url[offset] > '6') return false;
				if(url[offset] == '6' && url[offset+1] > '5') return false;
				if(url[offset] == '6' && url[offset+1] == '5' && url[offset+2] > '5') return false;
				if(url[offset] == '6' && url[offset+1] == '5' && url[offset+2] == '5' && url[offset+3] > '3') return false;
				if(url[offset] == '6' && url[offset+1] == '5' && url[offset+2] == '5' && url[offset+3] == '3' && url[offset+4] > '5') return false;
			}
		}
		tmp_len = i - offset;
		if (tmp_len == 0) {
			return false;
		}
		offset = i;
	}else{
		/* Default port: https=443, http=80 */
		tmp = output->is_tls ? "443" : "80";
		tmp_len = output->is_tls ? 3 : 2;
	}
	output->service = tmp;
	output->service_length = tmp_len;

	if(offset < len){
		output->path = &(url[offset]);
		output->path_length = len - offset;
	}else{
		output->path = default_path;
		output->path_length = sizeof(default_path) - 1;
	}
	return true;
}
