server:
  port: 8085

spring:
  application:
    name: event-handler
  datasource:
    url: jdbc:postgresql://localhost:5432/event_handler
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# Configuração do webhook dispatcher
webhook:
  timeout-ms: 5000
  max-retries: 3
  retry-delay-ms: 2000