spring:

  application:
    name: bff

  threads:
    virtual:
      enabled: true

  mvc:
    async:
      request-timeout: -1

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:spring-bff}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}

  session:
    store-type: redis
    timeout: 30m

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT:8083}
  tomcat:
    max-http-form-post-size: 10MB
app:
  frontend-url: ${FRONTEND_URL}
  gov-api-url: ${GOV_API_URL}
  keycloak-admin-url: ${KEYCLOAK_ADMIN_URL}

logging:
  level:
    org.springframework.security: ${LOG_LEVEL_SECURITY:WARN}
    org.springframework.security.oauth2: ${LOG_LEVEL_OAUTH:WARN}
    org.springframework.session: WARN
    org.springframework.data.redis: WARN
    org.springframework.web.servlet.DispatcherServlet: DEBUG
