server:
  port: 8091

grpc:
  broker:
    host: ${BROKER_HOST:localhost}
    port: ${BROKER_PORT:50051}
    topic: ${BROKER_TOPIC:status}
    error-topic: ${BROKER_ERROR_TOPIC:error}
    tls: ${BROKER_TLS:false}

spring:
  application:
    name: agent-grpc
