package com.eric.governanceApi.governanceApi.enums;

public enum AuditAction {
    COMMAND_SENT,
    FIRMWARE_UPLOADED,
    FIRMWARE_DEPLOYED,
    FIRMWARE_DEPRECATED,
    FIRMWARE_SET_PROVISIONING,
    DEVICE_REVOKED,
    FLASH_PACKAGE_GENERATED,
    SENSOR_REGISTERED,
    GROUP_CREATED,
    GROUP_DELETED,
    DEVICE_ADDED_TO_GROUP,
    DEVICE_REMOVED_FROM_GROUP,
    USER_ASSIGNED_TO_GROUP,
    USER_REMOVED_FROM_GROUP
}
