package com.eric.governanceApi.governanceApi.enums;

public enum ErrorCode {

    // 404 — resource not found
    DEVICE_NOT_FOUND,
    FIRMWARE_NOT_FOUND,
    FIRMWARE_VERSION_NOT_FOUND,
    GROUP_NOT_FOUND,
    SENSOR_NOT_FOUND,
    USER_NOT_FOUND,
    ENDPOINT_NOT_FOUND,
    COMMAND_NOT_FOUND,
    RESOURCE_NOT_FOUND,

    // 409 — conflict
    FIRMWARE_NAME_DUPLICATE,
    FIRMWARE_VERSION_DUPLICATE,
    DEVICE_ALREADY_PROVISIONED,
    GROUP_MEMBERSHIP_EXISTS,
    SENSOR_NAME_DUPLICATE,
    CONFLICT,

    // 403 — access denied
    ADMIN_ONLY,
    OWNER_REQUIRED,
    MEMBER_REQUIRED,
    NOT_IN_GROUP_SCOPE,
    ACCESS_DENIED,

    // 400 — bad request
    VALIDATION_FAILED,
    MALFORMED_JSON,
    PARAMETER_TYPE_MISMATCH,
    PROVISIONING_TOKEN_EXPIRED,
    PROVISIONING_TOKEN_INVALID,
    FIRMWARE_VERSION_DEPRECATED,
    FIRMWARE_MUST_BE_PLATFORM,
    OTA_SAME_VERSION,
    INVALID_STATE_TRANSITION,
    INVALID_REQUEST,

    // 503 / 500 — infrastructure
    STORAGE_UNAVAILABLE,
    AGENT_UNREACHABLE,
    INFRASTRUCTURE_UNAVAILABLE,
    INTERNAL_ERROR
}
