services:

  iot-broker:
    image: iegomez/mosquitto-go-auth:3.0.0-mosquitto_2.0.18
    container_name: iot-broker
    command: /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf
    ports:
      - "127.0.0.1:11883:1883"
      - "127.0.0.1:18884:8884"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - iot-broker-data:/mosquitto/data
      - iot-broker-log:/mosquitto/log
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 128M
    restart: unless-stopped
    networks: [iot-net]

volumes:
  iot-broker-data:
  iot-broker-log:

networks:
  iot-net:
    external: true
