server:
  port: 8087

mqtt:
  broker-url: ssl://${HOST_IP}:8883
  client-id: agent-mqtt
  topic: status/#
  error-topic: error/#
  telemetry-topic: telemetry/#
  keystore-path: classpath:certs/agents.p12
  keystore-password: ${AGENT_KEYSTORE_PASS}
  truststore-path: classpath:certs/truststore.p12
  truststore-password: ${AGENT_TRUSTSTORE_PASS}

govapi:
  url: ${GOVAPI_URL:http://localhost:8082}

event-handler:
  url: ${EVENT_HANDLER_URL:http://localhost:8085}

datalogger:
  url: http://localhost:8081

spring:
  data:                          
    redis:
      host: ${REDIS_STREAMS_HOST:localhost}
      port: ${REDIS_STREAMS_PORT:6380}
      # password: ${REDIS_STREAMS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2

  application:
    name: agent-mqtt
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
      client:
        registration:
          govapi:
            client-id: agent-mqtt
            client-secret: ${AGENT_MQTT_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          govapi:
            token-uri: ${KEYCLOAK_ISSUER_URI}/protocol/openid-connect/token
